import type { ResourceModule } from "./admin-resource-api";

export const adminModules: ResourceModule[] = [
  {
    slug: "users",
    title: "Users",
    eyebrow: "Access",
    description: "Manage admin user records that are allowed into the dashboard.",
    table: "admin_users",
    primaryLabel: "email",
    readOnly: true,
    fields: [
      { key: "email", label: "Email", type: "text", required: true },
      { key: "full_name", label: "Full name", type: "text" },
      { key: "role", label: "Role", type: "select", options: ["owner", "manager", "staff"], required: true },
    ],
  },
  {
    slug: "roles",
    title: "Roles",
    eyebrow: "Access",
    description: "Create role bundles for admin capabilities.",
    table: "roles",
    primaryLabel: "name",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "permissions", label: "Permissions JSON", type: "json" },
    ],
  },
  {
    slug: "permissions",
    title: "Permissions",
    eyebrow: "Access",
    description: "Track permission keys by admin module.",
    table: "permissions",
    primaryLabel: "key",
    fields: [
      { key: "key", label: "Key", type: "text", required: true },
      { key: "module", label: "Module", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    slug: "brands",
    title: "Brands",
    eyebrow: "Catalog",
    description: "Manage brand identities for the product catalog.",
    table: "brands",
    primaryLabel: "name",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "logo_url", label: "Logo URL", type: "text" },
      { key: "status", label: "Status", type: "select", options: ["active", "draft", "archived"], required: true },
    ],
  },
  {
    slug: "collections",
    title: "Collections",
    eyebrow: "Catalog",
    description: "Build merchandising collections for campaigns and storefront sections.",
    table: "collections",
    primaryLabel: "name",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "image_url", label: "Image URL", type: "text" },
      { key: "status", label: "Status", type: "select", options: ["active", "draft", "archived"], required: true },
      { key: "starts_at", label: "Starts at", type: "datetime" },
      { key: "ends_at", label: "Ends at", type: "datetime" },
    ],
  },
  {
    slug: "inventory",
    title: "Inventory",
    eyebrow: "Operations",
    description: "Track SKU quantity, reserved stock and reorder thresholds.",
    table: "inventory_items",
    primaryLabel: "sku",
    fields: [
      { key: "sku", label: "SKU", type: "text", required: true },
      { key: "quantity", label: "Quantity", type: "number", required: true },
      { key: "reserved_quantity", label: "Reserved quantity", type: "number" },
      { key: "reorder_point", label: "Reorder point", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["in_stock", "low_stock", "out_of_stock"], required: true },
    ],
  },
  {
    slug: "warehouses",
    title: "Warehouses",
    eyebrow: "Operations",
    description: "Manage fulfillment and stock locations.",
    table: "warehouses",
    primaryLabel: "name",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "code", label: "Code", type: "text", required: true },
      { key: "address", label: "Address", type: "textarea" },
      { key: "city", label: "City", type: "text" },
      { key: "country", label: "Country", type: "text" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"], required: true },
    ],
  },
  {
    slug: "suppliers",
    title: "Suppliers",
    eyebrow: "Operations",
    description: "Maintain supplier contacts and status.",
    table: "suppliers",
    primaryLabel: "name",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "contact_name", label: "Contact name", type: "text" },
      { key: "email", label: "Email", type: "text" },
      { key: "phone", label: "Phone", type: "text" },
      { key: "address", label: "Address", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"], required: true },
    ],
  },
  {
    slug: "returns",
    title: "Returns",
    eyebrow: "Orders",
    description: "Process return requests and received merchandise.",
    table: "returns",
    primaryLabel: "customer_name",
    fields: [
      { key: "customer_name", label: "Customer name", type: "text", required: true },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["requested", "approved", "rejected", "received", "closed"], required: true },
      { key: "total", label: "Total", type: "number" },
    ],
  },
  {
    slug: "refunds",
    title: "Refunds",
    eyebrow: "Orders",
    description: "Track refund approvals and payouts.",
    table: "refunds",
    primaryLabel: "reason",
    fields: [
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["pending", "approved", "paid", "rejected"], required: true },
    ],
  },
  {
    slug: "payments",
    title: "Payments",
    eyebrow: "Finance",
    description: "Record payment provider references and status.",
    table: "payments",
    primaryLabel: "reference",
    fields: [
      { key: "provider", label: "Provider", type: "text", required: true },
      { key: "reference", label: "Reference", type: "text" },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "status", label: "Status", type: "select", options: ["pending", "paid", "failed", "refunded"], required: true },
      { key: "paid_at", label: "Paid at", type: "datetime" },
    ],
  },
  {
    slug: "shipping",
    title: "Shipping",
    eyebrow: "Operations",
    description: "Configure shipping methods and base fees.",
    table: "shipping_methods",
    primaryLabel: "name",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "carrier", label: "Carrier", type: "text" },
      { key: "base_fee", label: "Base fee", type: "number" },
      { key: "estimated_days", label: "Estimated days", type: "text" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"], required: true },
    ],
  },
  {
    slug: "customers",
    title: "Customers",
    eyebrow: "CRM",
    description: "Manage customer profiles, contact information and tags.",
    table: "customers",
    primaryLabel: "full_name",
    fields: [
      { key: "full_name", label: "Full name", type: "text", required: true },
      { key: "email", label: "Email", type: "text" },
      { key: "phone", label: "Phone", type: "text" },
      { key: "address", label: "Address", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["active", "blocked"], required: true },
      { key: "tags", label: "Tags JSON", type: "json" },
    ],
  },
  {
    slug: "reviews",
    title: "Reviews",
    eyebrow: "Community",
    description: "Moderate product reviews.",
    table: "reviews",
    primaryLabel: "title",
    fields: [
      { key: "customer_name", label: "Customer name", type: "text", required: true },
      { key: "rating", label: "Rating", type: "number", required: true },
      { key: "title", label: "Title", type: "text" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected"], required: true },
    ],
  },
  {
    slug: "coupons",
    title: "Coupons",
    eyebrow: "Promotions",
    description: "Manage coupon codes and validity windows.",
    table: "coupons",
    primaryLabel: "code",
    fields: [
      { key: "code", label: "Code", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "discount_type", label: "Type", type: "select", options: ["percentage", "fixed"], required: true },
      { key: "discount_value", label: "Value", type: "number", required: true },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive", "expired"], required: true },
    ],
  },
  {
    slug: "discounts",
    title: "Discounts",
    eyebrow: "Promotions",
    description: "Create automatic discount rules.",
    table: "discounts",
    primaryLabel: "name",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "discount_type", label: "Type", type: "select", options: ["percentage", "fixed"], required: true },
      { key: "discount_value", label: "Value", type: "number", required: true },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive", "expired"], required: true },
    ],
  },
  {
    slug: "gift-cards",
    title: "Gift Cards",
    eyebrow: "Promotions",
    description: "Issue and manage gift card balances.",
    table: "gift_cards",
    primaryLabel: "code",
    fields: [
      { key: "code", label: "Code", type: "text", required: true },
      { key: "recipient_email", label: "Recipient email", type: "text" },
      { key: "initial_balance", label: "Initial balance", type: "number", required: true },
      { key: "current_balance", label: "Current balance", type: "number", required: true },
      { key: "status", label: "Status", type: "select", options: ["active", "redeemed", "disabled"], required: true },
    ],
  },
  {
    slug: "cms",
    title: "CMS",
    eyebrow: "Content",
    description: "Manage structured CMS pages.",
    table: "cms_pages",
    primaryLabel: "title",
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "content", label: "Content JSON", type: "json" },
      { key: "status", label: "Status", type: "select", options: ["draft", "published", "archived"], required: true },
      { key: "published_at", label: "Published at", type: "datetime" },
    ],
  },
  {
    slug: "media",
    title: "Media Library",
    eyebrow: "Content",
    description: "Catalog uploaded media assets and metadata.",
    table: "media_assets",
    primaryLabel: "title",
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "url", label: "URL", type: "text", required: true },
      { key: "asset_type", label: "Type", type: "select", options: ["image", "video", "document"], required: true },
      { key: "alt_text", label: "Alt text", type: "text" },
      { key: "folder", label: "Folder", type: "text" },
    ],
  },
  {
    slug: "advertisements",
    title: "Advertisement Management",
    eyebrow: "Marketing",
    description: "Manage placements, creative assets and campaign windows.",
    table: "advertisements",
    primaryLabel: "name",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "placement", label: "Placement", type: "text", required: true },
      { key: "image_url", label: "Image URL", type: "text" },
      { key: "target_url", label: "Target URL", type: "text" },
      { key: "status", label: "Status", type: "select", options: ["draft", "active", "paused", "archived"], required: true },
    ],
  },
  {
    slug: "homepage",
    title: "Homepage Builder",
    eyebrow: "Content",
    description: "Compose homepage sections and publication state.",
    table: "homepage_sections",
    primaryLabel: "title",
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "section_type", label: "Section type", type: "text", required: true },
      { key: "content", label: "Content JSON", type: "json" },
      { key: "sort_order", label: "Sort order", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["draft", "published", "archived"], required: true },
    ],
  },
  {
    slug: "marketing",
    title: "Marketing",
    eyebrow: "Growth",
    description: "Plan and track marketing campaign records.",
    table: "marketing_campaigns",
    primaryLabel: "name",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "channel", label: "Channel", type: "text", required: true },
      { key: "budget", label: "Budget", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["draft", "active", "paused", "completed"], required: true },
    ],
  },
  {
    slug: "notifications",
    title: "Notifications",
    eyebrow: "System",
    description: "Create and triage admin notifications.",
    table: "notifications",
    primaryLabel: "title",
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "body", label: "Body", type: "textarea" },
      { key: "channel", label: "Channel", type: "text", required: true },
      { key: "status", label: "Status", type: "select", options: ["unread", "read", "archived"], required: true },
    ],
  },
  {
    slug: "settings",
    title: "Settings",
    eyebrow: "System",
    description: "Manage store-level settings as structured JSON values.",
    table: "store_settings",
    primaryLabel: "key",
    fields: [
      { key: "key", label: "Key", type: "text", required: true },
      { key: "value", label: "Value JSON", type: "json" },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    slug: "audit-logs",
    title: "Audit Logs",
    eyebrow: "System",
    description: "Review immutable admin activity captured by database triggers.",
    table: "audit_logs",
    primaryLabel: "action",
    readOnly: true,
    fields: [
      { key: "action", label: "Action", type: "text" },
      { key: "resource", label: "Resource", type: "text" },
      { key: "resource_id", label: "Resource ID", type: "text" },
      { key: "metadata", label: "Metadata JSON", type: "json" },
    ],
  },
];

export function getAdminModule(slug: string): ResourceModule | undefined {
  return adminModules.find((module) => module.slug === slug);
}
